In [1]:
from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("manoz.csv")
df

Unnamed: 0      NACCID  HISPORX  RACE  BIRTHYR  SEX  HANDED  DIABETES  \
0                0  NACC000385        0     1     1926    1       2         0   
1                1  NACC000385        0     1     1926    1       2         0   
2                2  NACC000385        0     1     1926    1       2         0   
3                3  NACC000385        0     1     1926    1       2         0   
4                4  NACC000385        0     1     1926    1       2         0   
...            ...         ...      ...   ...      ...  ...     ...       ...   
121093      121093   NACC90475        0     2     1936    2       2         1   
121094      121094   NACC90475        0     2     1936    2       2         1   
121095       12100  NACC999391        0     1     1918    1       2         0   
121096       12100  NACC999391        0     1     1918    1       2         0   
121097       12100  NACC999391        0     1     1918    1       2         0   

        HYPERTEN  HYPERCHO  ...  TOBAC30  TOBAC100  SMOKYRS  CVHATT  NACCMMSE  \
0              1         1  ...        0         1       15       1        24   
1              1         1  ...        0         1       20       1        22   
2              1         1  ...        0         1       17       1        21   
3              1         1  ...        0         1       17       1        20   
4              1         1  ...        0         1       20       1        16   
...          ...       ...  ...      ...       ...      ...     ...       ...   
121093         1         1  ...        0         0        0       0        25   
121094         1         1  ...        0         0        0       0        26   
121095         1         1  ...        0         1       40       1        28   
121096         1         1  ...        0         1       40       1        28   
121097         1         1  ...        0         1       40       1        27   

        NACCAGEB    NACCBMI  Impairment  CANCER  NACCALZD  
0             80   8.799999           4       0         1  
1             80  29.000000           4       0         1  
2             80  29.000000           4       0         1  
3             80  26.399999           4       1         1  
4             80  29.000000           4       1         1  
...          ...        ...         ...     ...       ...  
121093        70   8.799999           3       0         0  
121094        70   8.799999           4       1         0  
121095        87  26.799999           3       0         0  
121096        87  27.099999           4       0         1  
121097        87  25.500000           4       0         1  

[121098 rows x 26 columns]

In [3]:
df['Impairment'].value_counts()

1    54010
4    40676
3    20811
2     5601
Name: Impairment, dtype: int64

In [4]:
df1=df.get(['HISPORX','SEX','DIABETES','HYPERTEN','HYPERCHO','TOBAC30','ALCOHOL','NACCMMSE','CDRGLOB','CVHATT','NACCUDSD','CANCER','NACCALZD'])


In [5]:
# plt.scatter(df.NACCAGEB,df.NACCALZD,marker='+',color='red')

In [5]:
X=df[['HISPORX','SEX','DIABETES','HYPERTEN','HYPERCHO','TOBAC30','ALCOHOL','NACCMMSE','CDRGLOB','CVHATT','NACCALZD','CANCER']]
y=df['Impairment']

In [6]:
X

HISPORX  SEX  DIABETES  HYPERTEN  HYPERCHO  TOBAC30  ALCOHOL  \
0             0    1         0         1         1        0        0   
1             0    1         0         1         1        0        0   
2             0    1         0         1         1        0        0   
3             0    1         0         1         1        0        0   
4             0    1         0         1         1        0        0   
...         ...  ...       ...       ...       ...      ...      ...   
121093        0    2         1         1         1        0        0   
121094        0    2         1         1         1        0        0   
121095        0    1         0         1         1        0        0   
121096        0    1         0         1         1        0        0   
121097        0    1         0         1         1        0        0   

        NACCMMSE  CDRGLOB  CVHATT  NACCALZD  CANCER  
0             24      1.0       1         1       0  
1             22      1.0       1         1       0  
2             21      1.0       1         1       0  
3             20      1.0       1         1       1  
4             16      1.0       1         1       1  
...          ...      ...     ...       ...     ...  
121093        25      0.0       0         0       0  
121094        26      0.5       0         0       1  
121095        28      0.5       1         0       0  
121096        28      0.5       1         1       0  
121097        27      0.5       1         1       0  

[121098 rows x 12 columns]

In [7]:
y

0         4
1         4
2         4
3         4
4         4
         ..
121093    3
121094    4
121095    3
121096    4
121097    4
Name: Impairment, Length: 121098, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
X_train.describe()

HISPORX           SEX      DIABETES      HYPERTEN      HYPERCHO  \
count  96878.000000  96878.000000  96878.000000  96878.000000  96878.000000   
mean       0.021790      1.575094      0.244256      0.497130      0.507277   
std        0.571101      0.494331      0.429647      0.499994      0.499950   
min        0.000000      1.000000      0.000000      0.000000      0.000000   
25%        0.000000      1.000000      0.000000      0.000000      0.000000   
50%        0.000000      2.000000      0.000000      0.000000      1.000000   
75%        0.000000      2.000000      0.000000      1.000000      1.000000   
max       27.000000      2.000000      1.000000      1.000000      1.000000   

            TOBAC30       ALCOHOL      NACCMMSE       CDRGLOB        CVHATT  \
count  96878.000000  96878.000000  96878.000000  96878.000000  96878.000000   
mean       0.058796      0.174797     20.268503      0.587239      0.180815   
std        0.520452      0.379795     11.592368      0.793123      0.384867   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000     13.000000      0.000000      0.000000   
50%        0.000000      0.000000     26.000000      0.500000      0.000000   
75%        0.000000      0.000000     29.000000      1.000000      0.000000   
max        9.000000      1.000000     30.000000      3.000000      1.000000   

           NACCALZD        CANCER  
count  96878.000000  96878.000000  
mean       1.273509      0.072968  
std        0.738743      0.260085  
min        0.000000      0.000000  
25%        1.000000      0.000000  
50%        1.000000      0.000000  
75%        2.000000      0.000000  
max        2.000000      1.000000

In [11]:
y_test

68138    4
35694    2
23       4
19250    1
79754    1
        ..
57386    3
40415    3
3783     4
53244    4
73471    3
Name: Impairment, Length: 24220, dtype: int64

In [14]:
X_test

HISPORX  SEX  DIABETES  HYPERTEN  HYPERCHO  TOBAC30  ALCOHOL  NACCMMSE  \
68138        0    1         0         1         1        0        0        19   
35694        0    1         1         1         1        0        0        27   
23           0    2         0         1         1        0        0        14   
19250        0    2         0         1         0        0        0        29   
79754        0    2         0         0         0        0        0        29   
...        ...  ...       ...       ...       ...      ...      ...       ...   
57386        0    2         1         1         1        0        0        22   
40415        0    1         0         1         1        0        0         0   
3783         0    1         0         1         1        0        0        23   
53244        0    2         0         1         1        0        0         0   
73471        0    2         0         1         1        0        0        30   

       CDRGLOB  CVHATT  NACCALZD  CANCER  
68138      1.0       1         1       0  
35694      0.5       0         0       1  
23         1.0       0         0       0  
19250      0.0       0         2       0  
79754      0.0       0         2       0  
...        ...     ...       ...     ...  
57386      0.5       0         0       0  
40415      0.5       0         0       1  
3783       1.0       0         0       0  
53244      0.5       0         1       0  
73471      0.5       0         1       1  

[24220 rows x 12 columns]

In [15]:
X_train

HISPORX  SEX  DIABETES  HYPERTEN  HYPERCHO  TOBAC30  ALCOHOL  \
111601        0    2         1         0         0        0        1   
64218         0    1         0         0         0        0        0   
113214        0    2         0         1         1        1        0   
106845        0    1         0         1         1        0        0   
25937         0    2         0         0         0        0        0   
...         ...  ...       ...       ...       ...      ...      ...   
45891         0    2         0         0         0        0        0   
117952        0    1         0         1         1        0        0   
42613         0    2         0         0         0        0        0   
43567         0    2         1         0         0        0        1   
68268         0    2         0         1         0        0        0   

        NACCMMSE  CDRGLOB  CVHATT  NACCALZD  CANCER  
111601        30      0.0       1         2       0  
64218         28      0.0       0         2       0  
113214        28      0.0       0         2       0  
106845        23      0.5       0         0       0  
25937         30      0.0       0         2       0  
...          ...      ...     ...       ...     ...  
45891         29      0.0       0         2       0  
117952        30      0.0       0         2       1  
42613          0      1.0       0         1       0  
43567          0      0.0       1         2       0  
68268         24      0.5       0         1       0  

[96878 rows x 12 columns]

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
model = LogisticRegression()

In [18]:
model.fit(X_train, y_train)

/home/manu/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/manu/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
X_test

HISPORX  SEX  DIABETES  HYPERTEN  HYPERCHO  TOBAC30  ALCOHOL  NACCMMSE  \
68138        0    1         0         1         1        0        0        19   
35694        0    1         1         1         1        0        0        27   
23           0    2         0         1         1        0        0        14   
19250        0    2         0         1         0        0        0        29   
79754        0    2         0         0         0        0        0        29   
...        ...  ...       ...       ...       ...      ...      ...       ...   
57386        0    2         1         1         1        0        0        22   
40415        0    1         0         1         1        0        0         0   
3783         0    1         0         1         1        0        0        23   
53244        0    2         0         1         1        0        0         0   
73471        0    2         0         1         1        0        0        30   

       CDRGLOB  CVHATT  NACCALZD  CANCER  
68138      1.0       1         1       0  
35694      0.5       0         0       1  
23         1.0       0         0       0  
19250      0.0       0         2       0  
79754      0.0       0         2       0  
...        ...     ...       ...     ...  
57386      0.5       0         0       0  
40415      0.5       0         0       1  
3783       1.0       0         0       0  
53244      0.5       0         1       0  
73471      0.5       0         1       1  

[24220 rows x 12 columns]

In [20]:
pred = model.predict(X_test)
pred

array([4, 3, 4, ..., 4, 4, 3])

In [21]:
model.score(X_test,y_test)

0.8529727497935591

In [22]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[10703     0     0     0]
 [    0     0   859   236]
 [    0     0  2421  1789]
 [    0     0   677  7535]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     10703
           2       0.00      0.00      0.00      1095
           3       0.61      0.58      0.59      4210
           4       0.79      0.92      0.85      8212

    accuracy                           0.85     24220
   macro avg       0.60      0.62      0.61     24220
weighted avg       0.82      0.85      0.83     24220



/home/manu/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
