In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("manoz.csv")
df

Unnamed: 0      NACCID  HISPORX  RACE  BIRTHYR  SEX  HANDED  DIABETES  \
0                0  NACC000385        0     1     1926    1       2         0   
1                1  NACC000385        0     1     1926    1       2         0   
2                2  NACC000385        0     1     1926    1       2         0   
3                3  NACC000385        0     1     1926    1       2         0   
4                4  NACC000385        0     1     1926    1       2         0   
...            ...         ...      ...   ...      ...  ...     ...       ...   
121093      121093   NACC90475        0     2     1936    2       2         1   
121094      121094   NACC90475        0     2     1936    2       2         1   
121095       12100  NACC999391        0     1     1918    1       2         0   
121096       12100  NACC999391        0     1     1918    1       2         0   
121097       12100  NACC999391        0     1     1918    1       2         0   

        HYPERTEN  HYPERCHO  ...  TOBAC30  TOBAC100  SMOKYRS  CVHATT  NACCMMSE  \
0              1         1  ...        0         1       15       1        24   
1              1         1  ...        0         1       20       1        22   
2              1         1  ...        0         1       17       1        21   
3              1         1  ...        0         1       17       1        20   
4              1         1  ...        0         1       20       1        16   
...          ...       ...  ...      ...       ...      ...     ...       ...   
121093         1         1  ...        0         0        0       0        25   
121094         1         1  ...        0         0        0       0        26   
121095         1         1  ...        0         1       40       1        28   
121096         1         1  ...        0         1       40       1        28   
121097         1         1  ...        0         1       40       1        27   

        NACCAGEB    NACCBMI  Impairment  CANCER  NACCALZD  
0             80   8.799999           4       0         1  
1             80  29.000000           4       0         1  
2             80  29.000000           4       0         1  
3             80  26.399999           4       1         1  
4             80  29.000000           4       1         1  
...          ...        ...         ...     ...       ...  
121093        70   8.799999           3       0         0  
121094        70   8.799999           4       1         0  
121095        87  26.799999           3       0         0  
121096        87  27.099999           4       0         1  
121097        87  25.500000           4       0         1  

[121098 rows x 26 columns]

In [4]:
X=df[['HISPORX','SEX','DIABETES','HYPERTEN','HYPERCHO','TOBAC30','ALCOHOL','NACCMMSE','CDRGLOB','CVHATT','NACCALZD','CANCER']]
y=df['Impairment']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.naive_bayes import GaussianNB

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

In [8]:
gnb = GaussianNB()
gnb.fit(X_train, y_train) 

GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
pred = gnb.predict(X_test)
pred

array([4, 2, 4, ..., 4, 4, 3])

In [10]:
gnb.score(X_test,y_test)

0.8369942196531792

In [11]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[10673     0    16    14]
 [    0   413   549   133]
 [    0   684  2874   652]
 [    0   306  1594  6312]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     10703
           2       0.29      0.38      0.33      1095
           3       0.57      0.68      0.62      4210
           4       0.89      0.77      0.82      8212

    accuracy                           0.84     24220
   macro avg       0.69      0.71      0.69     24220
weighted avg       0.86      0.84      0.84     24220

